### PR TITLE
Rename pyPROPOSAL to proposal, fixes #85

### LINKED ISSUE #85: Rename pyPROPOSAL → proposal
pyPROPOSAL just looks strange and py is unecessary for a module.

py is often in the repo name but almost never in the module name.

Opinions?

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by sudojan** [comment]
Get the following Error when doing
`cmake -S . -B build`
`cmake --build build`

make[2]: *** No rule to make target `CMakeFiles/proposal.dir/depend'.  Stop.
make[1]: *** [CMakeFiles/proposal.dir/all] Error 2
make: *** [all] Error 2

**Comment by MaxNoe** [comment]
Are you on a case insensitive filesystem?

**Comment by MaxNoe** [comment]
Can you try again?

**Comment by sudojan** [comment]
Now it's working

**Comment by MaxNoe** [comment]
macOS case insensitive filename at it again. :rage:

**Pull request merged**
