### PR TITLE
Refactor CMake, fixes #64, #63, #11

### LINKED ISSUE #64: Use cmake properties instead of setting cxx flags
It's considered bad style to explicitly set compiler arguments such as `--std=c++11` instead of using cmake options such as:

```
target_compile_features(PROPOSAL PUBLIC cxx_std_11)
set_target_properties(PROPOSAL PROPERTIES CXX_EXTENSIONS OFF)
```

we should switch to this.

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by sudojan** [comment]
which minimal cmake version is really required?
3.10 as in `CMakeLists.txt`
or 3.8 as in `cmake/Standalone_CMakeLists.cmake`

**Comment by MaxNoe** [comment]
Seems to be 3.8, worked fine and lower is not possible as this version introduced support for the c++ standards https://cmake.org/cmake/help/v3.17/release/3.8.html

**Comment by MaxNoe** [comment]
I set it consistently now.

**Comment by MaxNoe** [comment]
And I also download cmake 3.8.2 on travis and use that so that we introduce changes that require a newer cmake version, the tests will break.

**Pull request merged**
